<!-- END CONTENT -->
</main>

<footer class="container pt-3">
  <p>This page is maintained by the <a href="http://gdcproject.org">GDC Developers</a>
     on <a href="https://github.com/D-Programming-GDC/gdcproject">github</a>.
  </p>
  <p>Verbatim copying and distribution of this entire article is permitted in
     any medium, provided this notice is preserved.
  </p>
</footer>

<script type="text/javascript">
  $('.nav-item[href="'+ window.location.pathname +'"]').addClass('active');
</script>
</body>

</html>
