<!DOCTYPE html>
<html lang="en">

<head>
<meta content="text/html; charset=UTF-8" http-equiv="content-type">
<meta name="keywords" content="GNU D Compiler, GDC, D programming language">
<meta name="description" content="GNU D Compiler">
<link rel="stylesheet" href="/style/bootstrap.min.css" type="text/css" media="all" charset="utf-8">
<link rel="stylesheet" href="/style/main.css" type="text/css" media="all" charset="utf-8">
<link rel="icon" href="/images/gdc-omoon.png" type="image/png">
<title>GDC - D Programming Language for GCC</title>
</head>

<body>
<div class="container">

<div class="header">
  <center class="page-header">
    <a href="/"><img src="/images/gdc-two-moons-small.png" alt="GDC Project Revived" width="200px"></a>
  </center>
  <ul class="nav navbar-default nav-justified">
    <li><a href="http://gdcproject.org">home</a></li>
    <li><a href="http://gdcproject.org/contributing">contributing</a></li>
    <li><a href="http://gdcproject.org/downloads">downloads</a></li>
    <li><a href="http://gdcproject.org/documentation">documentation</a></li>
    <li><a href="http://bugzilla.gdcproject.org">bugs</a></li>
    <li><a href="https://github.com/D-Programming-GDC/GDC">current&nbsp;git</a></li>
    <li><a href="http://forum.dlang.org/group/D.gnu">mailing&nbsp;lists</a></li>
    <li><a href="http://wiki.gdcproject.org">wiki</a></li>
  </ul>
  <a style="background: url('/images/blacktocat.png') #0090ff no-repeat 95% 50%;"
     id="forkme_banner" href="https://github.com/D-Programming-GDC">View on GitHub</a>
</div>

<div class="page">
<!-- BEGIN CONTENT -->
