<!DOCTYPE html>
<html lang="en">

<head>
  <meta content="text/html; charset=UTF-8" http-equiv="content-type">
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="keywords" content="GNU D Compiler, GDC, D programming language">
  <meta name="description" content="GNU D Compiler">
  <title>GDC - D Programming Language for GCC</title>
  <link rel="icon" href="/images/gdc-omoon.png" type="image/png">
  <link rel="stylesheet" href="/style/bootstrap.min.css" type="text/css" media="all" charset="utf-8">
  <link rel="stylesheet" href="/style/main.css" type="text/css" media="all" charset="utf-8">
  <script src="/js/jquery.min.js"></script>
  <script src="/js/bootstrap.min.js"></script>
</head>

<body>

<header class="container">
  <nav class="navbar navbar-expand-lg flex-lg-column navbar-light bg-light">
    <a class="navbar-brand" href="/">
      <img alt="GDC Project Revived" src="/images/gdc-two-moons-small.png" />
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#menu">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div id="menu" class="collapse navbar-collapse">
      {{ templates/menu.inc }}
    </div>
  </nav>
</header>

<main class="container pt-4">
<!-- BEGIN CONTENT -->
