<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>

<head>
<meta content="text/html; charset=UTF-8" http-equiv="content-type">
<meta name="keywords" content="GNU D Compiler, GDC, D programming language">
<meta name="description" content="GNU D Compiler">
<link rel="stylesheet" href="/style/main.css" type="text/css" media="all" charset="utf-8">
<link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon">
<title>GDC - D Programming Language for GCC</title>
</head>

<body>

<div class="header">
<center><a href="/"><img src="/images/gdc-two-moons-small.png" alt="GDC Project Revived" width="200px"></a></center>

<center>
<small>
[<a href="http://gdcproject.org">home</a>]
[<a href="http://gdcproject.org/contributing">contributing</a>]
[<a href="http://gdcproject.org/downloads">downloads</a>]
[<a href="http://gdcproject.org/documentation">documentation</a>]
[<a href="http://bugzilla.gdcproject.org">bugs</a>]
[<a href="https://github.com/D-Programming-GDC/GDC">current git</a>]
[<a href="http://forum.dlang.org/group/D.gnu">mailing lists</a>]
[<a href="http://wiki.gdcproject.org">wiki</a>]
</small>
</center>

<a style="background: url('/images/blacktocat.png') #0090ff no-repeat 95% 50%;"
   id="forkme_banner" href="https://github.com/D-Programming-GDC">View on GitHub</a>
</div>

<div class="page">
<!-- BEGIN CONTENT -->
