<div class="navbar-nav">
  <a class="nav-item nav-link ml-3" href="/">home</a>
  <a class="nav-item nav-link ml-3" href="/contributing">contributing</a>
  <a class="nav-item nav-link ml-3" href="/downloads">downloads</a>
  <a class="nav-item nav-link ml-3" href="/documentation">documentation</a>
  <a class="nav-item nav-link ml-3" href="http://bugzilla.gdcproject.org">bugs</a>
  <a class="nav-item nav-link ml-3" href="https://github.com/D-Programming-GDC/GDC">current&nbsp;git</a>
  <a class="nav-item nav-link ml-3" href="http://forum.dlang.org/group/D.gnu">mailing&nbsp;lists</a>
  <a class="nav-item nav-link ml-3" href="http://wiki.gdcproject.org">wiki</a>
</div>
